### ISSUE TITLE
FIXME: discuss variable abbreviation

### ISSUE THREAD

**Issue by ariedamuco** [datacarpentry/stata-economics#24]
@ariedamuco

**Comment by ariedamuco** [comment]
@korenmiklos please check if this is addressed.

**Comment by korenmiklos** [comment]
Sorry, I meant variable name *wildcards* such as `gdp*` and `gdp_?`. We don't want them to abbreviate. Can you please add this to Episode 1 and submit a new PR?

**Comment by ariedamuco** [comment]
Done. Check Episode 1.
