### ISSUE TITLE
Discuss and decide whether to move `append` episode after `forvalues` episode

### ISSUE THREAD

**Issue by korenmiklos** [datacarpentry/stata-economics#32]
I almost never use `append` without a loop, so this would be quite natural. But in terms of "topics," `append` belongs more after "transform data," whereas `forvalues` seems a more advanced topic. Please discuss merits here.

**Comment by ariedamuco** [comment]
I would leave append to "transform data". After they are exposed to loops students should be able to link separate concepts (and append data using loops). Maybe we can show that they can loop through all the files that contain the word "WDI"...not sure if useful at this point.

**Comment by ariedamuco** [comment]
One possibility is to include `append` as a challenge in the `loops` episode. Have students generate temporary datasets for each year, say 2010-2017, and append these datasets together. A bit forced but could work. What do you think?

**Comment by korenmiklos** [comment]
I have already create these appendable chunks in 0498fc. Do you want to add this challenge?
