### ISSUE TITLE
Finalize setup.md for workshop

### ISSUE THREAD

**Issue by korenmiklos** [datacarpentry/stata-economics#34]

**Comment by ariedamuco** [comment]
#41 belongs here.

**Comment by korenmiklos** [comment]
We need a separate workshop site. https://github.com/korenmiklos/2019-08-30-EEA-Manchester

**Comment by korenmiklos** [comment]
Fixed by https://github.com/korenmiklos/2019-08-30-EEA-Manchester/commit/12679951cbbd136d043797c04273c9a2d7d55f7e
