### ISSUE TITLE
BLOCKING: change folder structure in all input and output statements in all episodes

### ISSUE THREAD

**Issue by korenmiklos** [datacarpentry/stata-economics#73]
I create a deeper folder structure in the new data package: https://zenodo.org/record/3477935 

This is both to encourage more modular organization, but also to help the shell episode, which needs several layers of folder structures.

Please go through episodes 1-6 and change each `use`, `import`, `save` etc statement to match the new folder structure.

**Comment by andrasvereckei** [comment]
@korenmiklos What should be the working directory? 
1. stata-economics
2. dc-economics-v2.0 

Now both of them are in the material.

**Comment by korenmiklos** [comment]
`dc-economics-v2.0` is correct but is too long. Shall we add a note in the "Setup instructions" to rename the folder to `stata-economics`?

**Comment by andrasvereckei** [comment]
> stata-economics

Absolutely! I already chose `stata-economics` for working folder name.
